In [1]:
import torch

In [9]:
x = (torch.zeros(1), torch.zeros(1))

print(x)



(tensor([0.]), tensor([0.]))


In [10]:
def pp(a, b, c):
    print(a, b, c)

In [14]:
a = torch.tensor([ 1, 2, 3, 4, 5])

print(a)

print(a.view(len(a), 1, -1))

tensor([1, 2, 3, 4, 5])
tensor([[[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]]])
