In [11]:
import sys
sys.path.append('..')

from models.JoaoNet import *

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, TensorDataset
import torchvision
from torchvision.transforms import ToTensor
from torchvision import datasets
import matplotlib.pyplot as plt


import os
import numpy as np
from datetime import datetime as dt

model = JoaoNetWithExitsCIFAR10()

print(model.backbone)
print(model.exits)

Sequential(
  (0): Sequential(
    (0): Conv2d(3, 96, kernel_size=(3, 3), stride=(1, 1))
    (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (1): Sequential(
    (0): Conv2d(96, 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2))
    (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (2): Sequential(
    (0): Conv2d(256, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
  )
)
Sequential(
  (0): Sequential(
    (0)

In [31]:
transform = ToTensor()

batch_size = 10

train_data   = datasets.CIFAR10(root='../data', train=True, download=True, transform=transform)
test_data    = datasets.CIFAR10(root='../data', train=False, download=True, transform=transform)
train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
test_loader  = DataLoader(test_data, batch_size=batch_size, shuffle=False)

Files already downloaded and verified
Files already downloaded and verified


In [57]:
for i, (X_train, y_train) in enumerate(train_data):
    X_train = X_train
    y_train = y_train
    break

x = X_train
print(x.shape)  
x = x.view(1,3,32,32)
print(x.shape)
x = model.backbone[0](x)
print(x.shape)

# x = model.backbone[1](x)
# print(x.shape)

# x = model.backbone[2](x)
# print(x.shape)

x = model.exits[0](x)
print(x.shape)

print(x)

x = nn.functional.softmax(x, dim=-1)

print(x)

x = torch.max(x, 1)

print(x[0])

# print(x[0].item())





# x = nn.MaxPool2d(kernel_size=5, stride=2)(x)
# print(x.shape)

torch.Size([3, 32, 32])
torch.Size([1, 3, 32, 32])
torch.Size([1, 96, 14, 14])
torch.Size([1, 10])
tensor([[ 2.3695, -1.4995,  0.4626,  1.8418,  0.3608, -0.3247,  4.1519,  1.8668,
         -0.3093, -2.9795]], grad_fn=<AddmmBackward0>)
tensor([[1.1650e-01, 2.4323e-03, 1.7305e-02, 6.8729e-02, 1.5629e-02, 7.8746e-03,
         6.9250e-01, 7.0470e-02, 7.9971e-03, 5.5369e-04]],
       grad_fn=<SoftmaxBackward0>)
tensor([0.6925], grad_fn=<MaxBackward0>)


In [51]:
a = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b = torch.tensor([0, 1, 2])
c = [0, 1, 2]
mask = b >= 1

print(a)
print(b)
print(mask)



tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([0, 1, 2])
tensor([False,  True,  True])
